# This is a Docker container based on a minimal Ubuntu installation that 
# includes conda-forge's mambaforge installer pre-installed at /opt/conda. 
# The container is build for amd64, arm64 and ppc64le. 
FROM condaforge/mambaforge:latest

# Set working directory in the container.
WORKDIR /cdlearn_app

# Install basic dependencies.
RUN mamba install -y \
    matplotlib \
    cartopy \
    xarray \
    scikit-learn \
    pandas \
    dask \
    tqdm

# Install development dependencies.
RUN mamba install -y \
    jupyterlab

# Copy our package.
COPY ./cdlearn ./cdlearn
COPY ./colormaps ./colormaps

# The command we want to run when the container starts.
CMD ["jupyter-lab","--ip=0.0.0.0","--no-browser","--allow-root"]
